var VERSION                    = "1.6.1";
var MIN_ANIMATION_INCREMENT    = 1;
var MAX_ANIMATION_INCREMENT    = 500;
var ANIMATION_INTERVAL_MS      = 50;
var ANIMATION_EXPONENT         = 3.0;
var ZOOM_ANIMATION_DURATION_MS = 1000;
var DATE_FORMATS               = ["dd-mmm-yyyy", "mmm-dd-yyyy", "yyyy-mmm-dd", "yyyy-dd-mmm"];
var DISTANCE_INCREASING_COLOR  = "red";
var DISTANCE_DECREASING_COLOR  = "green";
