import QtQuick 2.0

QtObject
{
    property list<Star> stars:
    [
        Star { name: "Sirius";            rightAscensionHours: 06; rightAscensionMinutes: 45; declination: -16.7; magnitude:-1.46 },
        Star { name: "Canopus";           rightAscensionHours: 06; rightAscensionMinutes: 24; declination: -52.7; magnitude:-0.73 },
        Star { name: "Rigil Kentaurus";   rightAscensionHours: 14; rightAscensionMinutes: 40; declination: -60.8; magnitude:-0.29 },
        Star { name: "Arcturus";          rightAscensionHours: 14; rightAscensionMinutes: 16; declination: +19.2; magnitude:-0.05 },
        Star { name: "Vega";              rightAscensionHours: 18; rightAscensionMinutes: 37; declination: +38.8; magnitude: 0.03 },
        Star { name: "Capella";           rightAscensionHours: 05; rightAscensionMinutes: 17; declination: +46.0; magnitude: 0.07 },
        Star { name: "Rigel";             rightAscensionHours: 05; rightAscensionMinutes: 15; declination:  -8.2; magnitude: 0.15 },
        Star { name: "Procyon";           rightAscensionHours: 07; rightAscensionMinutes: 39; declination:  +5.2; magnitude: 0.36 },
        Star { name: "Achernar";          rightAscensionHours: 01; rightAscensionMinutes: 38; declination: -57.2; magnitude: 0.45 },
        Star { name: "Betelgeuse";        rightAscensionHours: 05; rightAscensionMinutes: 55; declination:  +7.4; magnitude: 0.55 },
        Star { name: "Hadar";             rightAscensionHours: 14; rightAscensionMinutes: 04; declination: -60.4; magnitude: 0.61 },
        Star { name: "Altair";            rightAscensionHours: 19; rightAscensionMinutes: 51; declination:  +8.9; magnitude: 0.77 },
        Star { name: "Acrux";             rightAscensionHours: 12; rightAscensionMinutes: 27; declination: -63.1; magnitude: 0.79 },
        Star { name: "Aldebaran";         rightAscensionHours: 04; rightAscensionMinutes: 36; declination: +16.5; magnitude: 0.86 },
        Star { name: "Antares";           rightAscensionHours: 16; rightAscensionMinutes: 29; declination: -26.4; magnitude: 0.95 },
        Star { name: "Spica";             rightAscensionHours: 13; rightAscensionMinutes: 25; declination: -11.2; magnitude: 0.97 },
        Star { name: "Pollux";            rightAscensionHours: 07; rightAscensionMinutes: 45; declination: +28.0; magnitude: 1.14 },
        Star { name: "Fomalhaut";         rightAscensionHours: 22; rightAscensionMinutes: 58; declination: -29.6; magnitude: 1.15 },
        Star { name: "Deneb";             rightAscensionHours: 20; rightAscensionMinutes: 41; declination: +45.3; magnitude: 1.24 },
        Star { name: "Mimosa";            rightAscensionHours: 12; rightAscensionMinutes: 48; declination: -59.7; magnitude: 1.26 },
        Star { name: "Regulus";           rightAscensionHours: 10; rightAscensionMinutes: 08; declination: +12.0; magnitude: 1.36 },
        Star { name: "Adhara";            rightAscensionHours: 06; rightAscensionMinutes: 59; declination: -29.0; magnitude: 1.50 },
        Star { name: "Castor";            rightAscensionHours: 07; rightAscensionMinutes: 35; declination: +31.9; magnitude: 1.58 },
        Star { name: "Shaula";            rightAscensionHours: 17; rightAscensionMinutes: 34; declination: -37.1; magnitude: 1.62 },
        Star { name: "Gacrux";            rightAscensionHours: 12; rightAscensionMinutes: 31; declination: -57.1; magnitude: 1.63 },
        Star { name: "Bellatrix";         rightAscensionHours: 05; rightAscensionMinutes: 25; declination:  +6.3; magnitude: 1.64 },
        Star { name: "Elnath";            rightAscensionHours: 05; rightAscensionMinutes: 26; declination: +28.6; magnitude: 1.66 },
        Star { name: "Miaplacidus";       rightAscensionHours: 09; rightAscensionMinutes: 13; declination: -69.7; magnitude: 1.67 },
        Star { name: "Alnilam";           rightAscensionHours: 05; rightAscensionMinutes: 36; declination:  -1.2; magnitude: 1.69 },
        Star { name: "Alnair";            rightAscensionHours: 22; rightAscensionMinutes: 08; declination: -47.0; magnitude: 1.74 },
        Star { name: "Alnitak";           rightAscensionHours: 05; rightAscensionMinutes: 41; declination:  -1.9; magnitude: 1.75 },
        Star { name: "Alioth";            rightAscensionHours: 12; rightAscensionMinutes: 54; declination: +56.0; magnitude: 1.77 },
        Star { name: "Mirfak";            rightAscensionHours: 03; rightAscensionMinutes: 24; declination: +49.9; magnitude: 1.80 },
        Star { name: "Dubhe";             rightAscensionHours: 11; rightAscensionMinutes: 04; declination: +61.8; magnitude: 1.80 },
        Star { name: "Regor";             rightAscensionHours: 08; rightAscensionMinutes: 10; declination: -47.3; magnitude: 1.81 },
        Star { name: "Wezen";             rightAscensionHours: 07; rightAscensionMinutes: 08; declination: -26.4; magnitude: 1.83 },
        Star { name: "Kaus Australis";    rightAscensionHours: 18; rightAscensionMinutes: 24; declination: -34.4; magnitude: 1.84 },
        Star { name: "Alkaid";            rightAscensionHours: 13; rightAscensionMinutes: 48; declination: +49.3; magnitude: 1.86 },
        Star { name: "Sargas";            rightAscensionHours: 17; rightAscensionMinutes: 37; declination: -43.0; magnitude: 1.86 },
        Star { name: "Avior";             rightAscensionHours: 08; rightAscensionMinutes: 23; declination: -59.5; magnitude: 1.87 },
        Star { name: "Menkalinan";        rightAscensionHours: 06; rightAscensionMinutes: 00; declination: +44.9; magnitude: 1.90 },
        Star { name: "Atria";             rightAscensionHours: 16; rightAscensionMinutes: 49; declination: -69.0; magnitude: 1.92 },
        Star { name: "Alhena";            rightAscensionHours: 06; rightAscensionMinutes: 38; declination: +16.4; magnitude: 1.93 },
        Star { name: "Peacock";           rightAscensionHours: 20; rightAscensionMinutes: 26; declination: -56.7; magnitude: 1.93 },
        Star { name: "Koo She";           rightAscensionHours: 08; rightAscensionMinutes: 45; declination: -54.7; magnitude: 1.95 },
        Star { name: "Mirzam";            rightAscensionHours: 06; rightAscensionMinutes: 23; declination: -18.0; magnitude: 1.98 },
        Star { name: "Alphard";           rightAscensionHours: 09; rightAscensionMinutes: 28; declination:  -8.7; magnitude: 1.98 },
        Star { name: "Polaris";           rightAscensionHours: 02; rightAscensionMinutes: 32; declination: +89.3; magnitude: 1.99 },
        Star { name: "Algieba";           rightAscensionHours: 10; rightAscensionMinutes: 20; declination: +19.8; magnitude: 2.00 },
        Star { name: "Hamal";             rightAscensionHours: 02; rightAscensionMinutes: 07; declination: +23.5; magnitude: 2.01 },
        Star { name: "Diphda";            rightAscensionHours: 00; rightAscensionMinutes: 44; declination: -18.0; magnitude: 2.04 },
        Star { name: "Nunki";             rightAscensionHours: 18; rightAscensionMinutes: 55; declination: -26.3; magnitude: 2.05 },
        Star { name: "Menkent";           rightAscensionHours: 14; rightAscensionMinutes: 07; declination: -36.4; magnitude: 2.06 },
        Star { name: "Alpheratz";         rightAscensionHours: 00; rightAscensionMinutes: 08; declination: +29.1; magnitude: 2.07 },
        Star { name: "Mirach";            rightAscensionHours: 01; rightAscensionMinutes: 10; declination: +35.6; magnitude: 2.07 },
        Star { name: "Saiph";             rightAscensionHours: 05; rightAscensionMinutes: 48; declination:  -9.7; magnitude: 2.07 },
        Star { name: "Kochab";            rightAscensionHours: 14; rightAscensionMinutes: 51; declination: +74.2; magnitude: 2.07 },
        Star { name: "Al Dhanab";         rightAscensionHours: 22; rightAscensionMinutes: 43; declination: -46.9; magnitude: 2.07 },
        Star { name: "Rasalhague";        rightAscensionHours: 17; rightAscensionMinutes: 35; declination: +12.6; magnitude: 2.08 },
        Star { name: "Algol";             rightAscensionHours: 03; rightAscensionMinutes: 08; declination: +41.0; magnitude: 2.09 },
        Star { name: "Almach";            rightAscensionHours: 02; rightAscensionMinutes: 04; declination: +42.3; magnitude: 2.10 },
        Star { name: "Denebola";          rightAscensionHours: 11; rightAscensionMinutes: 49; declination: +14.6; magnitude: 2.14 },
        Star { name: "Cih";               rightAscensionHours: 00; rightAscensionMinutes: 57; declination: +60.7; magnitude: 2.15 },
        Star { name: "Muhlifain";         rightAscensionHours: 12; rightAscensionMinutes: 42; declination: -49.0; magnitude: 2.20 },
        Star { name: "Naos";              rightAscensionHours: 08; rightAscensionMinutes: 04; declination: -40.0; magnitude: 2.21 },
        Star { name: "Aspidiske";         rightAscensionHours: 09; rightAscensionMinutes: 17; declination: -59.3; magnitude: 2.21 },
        Star { name: "Alphecca";          rightAscensionHours: 15; rightAscensionMinutes: 35; declination: +26.7; magnitude: 2.22 },
        Star { name: "Suhail";            rightAscensionHours: 09; rightAscensionMinutes: 08; declination: -43.4; magnitude: 2.23 },
        Star { name: "Mizar";             rightAscensionHours: 13; rightAscensionMinutes: 24; declination: +54.9; magnitude: 2.23 },
        Star { name: "Sadr";              rightAscensionHours: 20; rightAscensionMinutes: 22; declination: +40.3; magnitude: 2.23 },
        Star { name: "Schedar";           rightAscensionHours: 00; rightAscensionMinutes: 41; declination: +56.5; magnitude: 2.24 },
        Star { name: "Eltanin";           rightAscensionHours: 17; rightAscensionMinutes: 57; declination: +51.5; magnitude: 2.24 },
        Star { name: "Mintaka";           rightAscensionHours: 05; rightAscensionMinutes: 32; declination:  -0.3; magnitude: 2.25 },
        Star { name: "Caph";              rightAscensionHours: 00; rightAscensionMinutes: 09; declination: +59.2; magnitude: 2.28 },
        Star { name: "";                  rightAscensionHours: 13; rightAscensionMinutes: 40; declination: -53.5; magnitude: 2.29 },
        Star { name: "Dschubba";          rightAscensionHours: 16; rightAscensionMinutes: 00; declination: -22.6; magnitude: 2.29 },
        Star { name: "Wei";               rightAscensionHours: 16; rightAscensionMinutes: 50; declination: -34.3; magnitude: 2.29 },
        Star { name: "Men";               rightAscensionHours: 14; rightAscensionMinutes: 42; declination: -47.4; magnitude: 2.30 },
        Star { name: "";                  rightAscensionHours: 14; rightAscensionMinutes: 36; declination: -42.2; magnitude: 2.33 },
        Star { name: "Merak";             rightAscensionHours: 11; rightAscensionMinutes: 02; declination: +56.4; magnitude: 2.34 },
        Star { name: "Izar";              rightAscensionHours: 14; rightAscensionMinutes: 45; declination: +27.1; magnitude: 2.35 },
        Star { name: "Enif";              rightAscensionHours: 21; rightAscensionMinutes: 44; declination:  +9.9; magnitude: 2.38 },
        Star { name: "Girtab";            rightAscensionHours: 17; rightAscensionMinutes: 42; declination: -39.0; magnitude: 2.39 },
        Star { name: "Ankaa";             rightAscensionHours: 00; rightAscensionMinutes: 26; declination: -42.3; magnitude: 2.40 },
        Star { name: "Phecda";            rightAscensionHours: 11; rightAscensionMinutes: 54; declination: +53.7; magnitude: 2.41 },
        Star { name: "Sabik";             rightAscensionHours: 17; rightAscensionMinutes: 10; declination: -15.7; magnitude: 2.43 },
        Star { name: "Scheat";            rightAscensionHours: 23; rightAscensionMinutes: 04; declination: +28.1; magnitude: 2.44 },
        Star { name: "Aludra";            rightAscensionHours: 07; rightAscensionMinutes: 24; declination: -29.3; magnitude: 2.45 },
        Star { name: "Alderamin";         rightAscensionHours: 21; rightAscensionMinutes: 19; declination: +62.6; magnitude: 2.45 },
        Star { name: "Markeb";            rightAscensionHours: 09; rightAscensionMinutes: 22; declination: -55.0; magnitude: 2.47 },
        Star { name: "Gienah";            rightAscensionHours: 20; rightAscensionMinutes: 46; declination: +34.0; magnitude: 2.48 },
        Star { name: "Markab";            rightAscensionHours: 23; rightAscensionMinutes: 05; declination: +15.2; magnitude: 2.49 },
        Star { name: "Menkar";            rightAscensionHours: 03; rightAscensionMinutes: 02; declination:  +4.1; magnitude: 2.54 },
        Star { name: "Han";               rightAscensionHours: 16; rightAscensionMinutes: 37; declination: -10.6; magnitude: 2.54 },
        Star { name: "Al Nair al Kent";   rightAscensionHours: 13; rightAscensionMinutes: 56; declination: -47.3; magnitude: 2.55 },
        Star { name: "Zosma";             rightAscensionHours: 11; rightAscensionMinutes: 14; declination: +20.5; magnitude: 2.56 },
        Star { name: "Graffias";          rightAscensionHours: 16; rightAscensionMinutes: 05; declination: -19.8; magnitude: 2.56 },
        Star { name: "Arneb";             rightAscensionHours: 05; rightAscensionMinutes: 33; declination: -17.8; magnitude: 2.58 },
        Star { name: "";                  rightAscensionHours: 12; rightAscensionMinutes: 08; declination: -50.7; magnitude: 2.58 },
        Star { name: "Gienah Ghurab";     rightAscensionHours: 12; rightAscensionMinutes: 16; declination: -17.5; magnitude: 2.58 },
        Star { name: "Ascella";           rightAscensionHours: 19; rightAscensionMinutes: 03; declination: -29.9; magnitude: 2.60 },
        Star { name: "Zubeneschamali";    rightAscensionHours: 15; rightAscensionMinutes: 17; declination:  -9.4; magnitude: 2.61 },
        Star { name: "Unukalhai";         rightAscensionHours: 15; rightAscensionMinutes: 44; declination:  +6.4; magnitude: 2.63 },
        Star { name: "Sheratan";          rightAscensionHours: 01; rightAscensionMinutes: 55; declination: +20.8; magnitude: 2.64 },
        Star { name: "Zubenelgenubi";     rightAscensionHours: 14; rightAscensionMinutes: 51; declination: -16.0; magnitude: 2.64 },
        Star { name: "Phact";             rightAscensionHours: 05; rightAscensionMinutes: 40; declination: -34.1; magnitude: 2.65 },
        Star { name: "";                  rightAscensionHours: 06; rightAscensionMinutes: 00; declination: +37.2; magnitude: 2.65 },
        Star { name: "Kraz";              rightAscensionHours: 12; rightAscensionMinutes: 34; declination: -23.4; magnitude: 2.65 },
        Star { name: "Ruchbah";           rightAscensionHours: 01; rightAscensionMinutes: 26; declination: +60.2; magnitude: 2.66 },
        Star { name: "Muphrid";           rightAscensionHours: 13; rightAscensionMinutes: 55; declination: +18.4; magnitude: 2.68 },
        Star { name: "Ke Kouan";          rightAscensionHours: 14; rightAscensionMinutes: 59; declination: -43.1; magnitude: 2.68 },
        Star { name: "Hassaleh";          rightAscensionHours: 04; rightAscensionMinutes: 57; declination: +33.2; magnitude: 2.69 },
        Star { name: "";                  rightAscensionHours: 10; rightAscensionMinutes: 47; declination: -49.4; magnitude: 2.69 },
        Star { name: "";                  rightAscensionHours: 12; rightAscensionMinutes: 37; declination: -69.1; magnitude: 2.69 },
        Star { name: "Lesath";            rightAscensionHours: 17; rightAscensionMinutes: 31; declination: -37.3; magnitude: 2.70 },
        Star { name: "";                  rightAscensionHours: 07; rightAscensionMinutes: 17; declination: -37.1; magnitude: 2.71 },
        Star { name: "Kaus Meridionalis"; rightAscensionHours: 18; rightAscensionMinutes: 21; declination: -29.8; magnitude: 2.72 },
        Star { name: "Tarazed";           rightAscensionHours: 19; rightAscensionMinutes: 46; declination: +10.6; magnitude: 2.72 },
        Star { name: "Yed Prior";         rightAscensionHours: 16; rightAscensionMinutes: 14; declination:  -3.7; magnitude: 2.73 },
        Star { name: "Aldhibain";         rightAscensionHours: 16; rightAscensionMinutes: 24; declination: +61.5; magnitude: 2.73 },
        Star { name: "";                  rightAscensionHours: 10; rightAscensionMinutes: 43; declination: -64.4; magnitude: 2.74 },
        Star { name: "Porrima";           rightAscensionHours: 12; rightAscensionMinutes: 42; declination:  -1.5; magnitude: 2.74 },
        Star { name: "Hatysa";            rightAscensionHours: 05; rightAscensionMinutes: 35; declination:  -5.9; magnitude: 2.75 },
        Star { name: "";                  rightAscensionHours: 13; rightAscensionMinutes: 21; declination: -36.7; magnitude: 2.75 },
        Star { name: "Cebalrai";          rightAscensionHours: 17; rightAscensionMinutes: 43; declination:  +4.6; magnitude: 2.76 },
        Star { name: "Kursa";             rightAscensionHours: 05; rightAscensionMinutes: 08; declination:  -5.1; magnitude: 2.78 },
        Star { name: "Kornephoros";       rightAscensionHours: 16; rightAscensionMinutes: 30; declination: +21.5; magnitude: 2.78 },
        Star { name: "";                  rightAscensionHours: 12; rightAscensionMinutes: 15; declination: -58.7; magnitude: 2.79 },
        Star { name: "Rastaban";          rightAscensionHours: 17; rightAscensionMinutes: 30; declination: +52.3; magnitude: 2.79 },
        Star { name: "Cor Caroli";        rightAscensionHours: 12; rightAscensionMinutes: 56; declination: +38.3; magnitude: 2.80 },
        Star { name: "";                  rightAscensionHours: 15; rightAscensionMinutes: 35; declination: -41.2; magnitude: 2.80 },
        Star { name: "Nihal";             rightAscensionHours: 05; rightAscensionMinutes: 28; declination: -20.8; magnitude: 2.81 }/*,
        Star { name: "Rutilicus";         rightAscensionHours: 16; rightAscensionMinutes: 41; declination: +31.6; magnitude: 2.81 },
        Star { name: "";                  rightAscensionHours: 00; rightAscensionMinutes: 26; declination: -77.3; magnitude: 2.82 },
        Star { name: "";                  rightAscensionHours: 16; rightAscensionMinutes: 36; declination: -28.2; magnitude: 2.82 },
        Star { name: "Kaus Borealis";     rightAscensionHours: 18; rightAscensionMinutes: 28; declination: -25.4; magnitude: 2.82 },
        Star { name: "Algenib";           rightAscensionHours: 00; rightAscensionMinutes: 13; declination: +15.2; magnitude: 2.83 },
        Star { name: "Turais";            rightAscensionHours: 08; rightAscensionMinutes: 08; declination: -24.3; magnitude: 2.83 },
        Star { name: "";                  rightAscensionHours: 15; rightAscensionMinutes: 55; declination: -63.4; magnitude: 2.83 },
        Star { name: "";                  rightAscensionHours: 03; rightAscensionMinutes: 54; declination: +31.9; magnitude: 2.84 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 25; declination: -55.5; magnitude: 2.84 },
        Star { name: "Choo";              rightAscensionHours: 17; rightAscensionMinutes: 32; declination: -49.9; magnitude: 2.84 },
        Star { name: "Alcyone";           rightAscensionHours: 03; rightAscensionMinutes: 47; declination: +24.1; magnitude: 2.85 },
        Star { name: "Vindemiatrix";      rightAscensionHours: 13; rightAscensionMinutes: 02; declination: +11.0; magnitude: 2.85 },
        Star { name: "Deneb Algedi";      rightAscensionHours: 21; rightAscensionMinutes: 47; declination: -16.1; magnitude: 2.85 },
        Star { name: "Head of Hydrus";    rightAscensionHours: 01; rightAscensionMinutes: 59; declination: -61.6; magnitude: 2.86 },
        Star { name: "";                  rightAscensionHours: 19; rightAscensionMinutes: 45; declination: +45.1; magnitude: 2.86 },
        Star { name: "Tejat";             rightAscensionHours: 06; rightAscensionMinutes: 23; declination: +22.5; magnitude: 2.87 },
        Star { name: "";                  rightAscensionHours: 15; rightAscensionMinutes: 19; declination: -68.7; magnitude: 2.87 },
        Star { name: "";                  rightAscensionHours: 22; rightAscensionMinutes: 19; declination: -60.3; magnitude: 2.87 },
        Star { name: "Acamar";            rightAscensionHours: 02; rightAscensionMinutes: 58; declination: -40.3; magnitude: 2.88 },
        Star { name: "Albaldah";          rightAscensionHours: 19; rightAscensionMinutes: 10; declination: -21.0; magnitude: 2.88 },
        Star { name: "Gomeisa";           rightAscensionHours: 07; rightAscensionMinutes: 27; declination: +08.3; magnitude: 2.89 },
        Star { name: "";                  rightAscensionHours: 15; rightAscensionMinutes: 59; declination: -26.1; magnitude: 2.89 },
        Star { name: "";                  rightAscensionHours: 03; rightAscensionMinutes: 58; declination: +40.0; magnitude: 2.90 },
        Star { name: "Alniyat";           rightAscensionHours: 16; rightAscensionMinutes: 21; declination: -25.6; magnitude: 2.90 },
        Star { name: "Albireo";           rightAscensionHours: 19; rightAscensionMinutes: 31; declination: +28.0; magnitude: 2.90 },
        Star { name: "Sadalsuud";         rightAscensionHours: 21; rightAscensionMinutes: 32; declination: -05.6; magnitude: 2.90 },
        Star { name: "";                  rightAscensionHours: 03; rightAscensionMinutes: 05; declination: +53.5; magnitude: 2.91 },
        Star { name: "";                  rightAscensionHours: 09; rightAscensionMinutes: 47; declination: -65.1; magnitude: 2.92 },
        Star { name: "Matar";             rightAscensionHours: 22; rightAscensionMinutes: 43; declination: +30.2; magnitude: 2.93 },
        Star { name: "";                  rightAscensionHours: 06; rightAscensionMinutes: 50; declination: -50.6; magnitude: 2.94 },
        Star { name: "Algorel";           rightAscensionHours: 12; rightAscensionMinutes: 30; declination: -16.5; magnitude: 2.94 },
        Star { name: "Sadalmelik";        rightAscensionHours: 22; rightAscensionMinutes: 06; declination: -00.3; magnitude: 2.95 },
        Star { name: "Zaurak";            rightAscensionHours: 03; rightAscensionMinutes: 58; declination: -13.5; magnitude: 2.97 },
        Star { name: "Alheka";            rightAscensionHours: 05; rightAscensionMinutes: 38; declination: +21.1; magnitude: 2.97 },
        Star { name: "Ras Elased Austr";  rightAscensionHours: 09; rightAscensionMinutes: 46; declination: +23.8; magnitude: 2.97 },
        Star { name: "Alnasl";            rightAscensionHours: 18; rightAscensionMinutes: 06; declination: -30.4; magnitude: 2.98 },
        Star { name: "";                  rightAscensionHours: 13; rightAscensionMinutes: 19; declination: -23.2; magnitude: 2.99 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 48; declination: -40.1; magnitude: 2.99 },
        Star { name: "Deneb el Okab";     rightAscensionHours: 19; rightAscensionMinutes: 05; declination: +13.9; magnitude: 2.99 },
        Star { name: "";                  rightAscensionHours: 02; rightAscensionMinutes: 10; declination: +35.0; magnitude: 3.00 },
        Star { name: "";                  rightAscensionHours: 11; rightAscensionMinutes: 10; declination: +44.5; magnitude: 3.00 },
        Star { name: "Pherkad Major";     rightAscensionHours: 15; rightAscensionMinutes: 21; declination: +71.8; magnitude: 3.00 },
        Star { name: "";                  rightAscensionHours: 16; rightAscensionMinutes: 52; declination: -38.0; magnitude: 3.00 },
        Star { name: "";                  rightAscensionHours: 21; rightAscensionMinutes: 54; declination: -37.4; magnitude: 3.00 },
        Star { name: "";                  rightAscensionHours: 03; rightAscensionMinutes: 43; declination: +47.8; magnitude: 3.01 },
        Star { name: "Phurad";            rightAscensionHours: 06; rightAscensionMinutes: 20; declination: -30.1; magnitude: 3.02 },
        Star { name: "";                  rightAscensionHours: 07; rightAscensionMinutes: 03; declination: -23.8; magnitude: 3.02 },
        Star { name: "Minkar";            rightAscensionHours: 12; rightAscensionMinutes: 10; declination: -22.6; magnitude: 3.02 },
        Star { name: "Almaaz";            rightAscensionHours: 05; rightAscensionMinutes: 02; declination: +43.8; magnitude: 3.03 },
        Star { name: "";                  rightAscensionHours: 12; rightAscensionMinutes: 46; declination: -68.1; magnitude: 3.04 },
        Star { name: "Seginus";           rightAscensionHours: 14; rightAscensionMinutes: 32; declination: +38.3; magnitude: 3.04 },
        Star { name: "Dabih";             rightAscensionHours: 20; rightAscensionMinutes: 21; declination: -14.8; magnitude: 3.05 },
        Star { name: "Mebsuta";           rightAscensionHours: 06; rightAscensionMinutes: 44; declination: +25.1; magnitude: 3.06 },
        Star { name: "Tania Australis";   rightAscensionHours: 10; rightAscensionMinutes: 22; declination: +41.5; magnitude: 3.06 },
        Star { name: "Tais";              rightAscensionHours: 19; rightAscensionMinutes: 13; declination: +67.7; magnitude: 3.07 },
        Star { name: "";                  rightAscensionHours: 18; rightAscensionMinutes: 18; declination: -36.8; magnitude: 3.10 },
        Star { name: "";                  rightAscensionHours: 08; rightAscensionMinutes: 55; declination: +05.9; magnitude: 3.11 },
        Star { name: "";                  rightAscensionHours: 10; rightAscensionMinutes: 50; declination: -16.2; magnitude: 3.11 },
        Star { name: "";                  rightAscensionHours: 11; rightAscensionMinutes: 36; declination: -63.0; magnitude: 3.11 },
        Star { name: "Persian";           rightAscensionHours: 20; rightAscensionMinutes: 38; declination: -47.3; magnitude: 3.11 },
        Star { name: "Wazn";              rightAscensionHours: 05; rightAscensionMinutes: 51; declination: -35.8; magnitude: 3.12 },
        Star { name: "Talita";            rightAscensionHours: 08; rightAscensionMinutes: 59; declination: +48.0; magnitude: 3.12 },
        Star { name: "";                  rightAscensionHours: 16; rightAscensionMinutes: 59; declination: -56.0; magnitude: 3.12 },
        Star { name: "Sarin";             rightAscensionHours: 17; rightAscensionMinutes: 15; declination: +24.8; magnitude: 3.12 },
        Star { name: "Ke Kwan";           rightAscensionHours: 14; rightAscensionMinutes: 59; declination: -42.1; magnitude: 3.13 },
        Star { name: "";                  rightAscensionHours: 09; rightAscensionMinutes: 21; declination: +34.4; magnitude: 3.14 },
        Star { name: "";                  rightAscensionHours: 09; rightAscensionMinutes: 31; declination: -57.0; magnitude: 3.16 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 15; declination: +36.8; magnitude: 3.16 },
        Star { name: "";                  rightAscensionHours: 06; rightAscensionMinutes: 38; declination: -43.2; magnitude: 3.17 },
        Star { name: "Al Haud";           rightAscensionHours: 09; rightAscensionMinutes: 33; declination: +51.7; magnitude: 3.17 },
        Star { name: "Aldhibah";          rightAscensionHours: 17; rightAscensionMinutes: 09; declination: +65.7; magnitude: 3.17 },
        Star { name: "";                  rightAscensionHours: 18; rightAscensionMinutes: 46; declination: -27.0; magnitude: 3.17 },
        Star { name: "Hoedus II";         rightAscensionHours: 05; rightAscensionMinutes: 07; declination: +41.2; magnitude: 3.18 },
        Star { name: "";                  rightAscensionHours: 14; rightAscensionMinutes: 43; declination: -65.0; magnitude: 3.18 },
        Star { name: "Tabit";             rightAscensionHours: 04; rightAscensionMinutes: 50; declination: +07.0; magnitude: 3.19 },
        Star { name: "";                  rightAscensionHours: 05; rightAscensionMinutes: 05; declination: -22.4; magnitude: 3.19 },
        Star { name: "";                  rightAscensionHours: 16; rightAscensionMinutes: 58; declination: +09.4; magnitude: 3.19 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 50; declination: -37.0; magnitude: 3.19 },
        Star { name: "";                  rightAscensionHours: 21; rightAscensionMinutes: 13; declination: +30.2; magnitude: 3.21 },
        Star { name: "Errai";             rightAscensionHours: 23; rightAscensionMinutes: 39; declination: +77.6; magnitude: 3.21 },
        Star { name: "";                  rightAscensionHours: 15; rightAscensionMinutes: 21; declination: -40.6; magnitude: 3.22 },
        Star { name: "Yed Posterior";     rightAscensionHours: 16; rightAscensionMinutes: 18; declination: -04.7; magnitude: 3.23 },
        Star { name: "Alava";             rightAscensionHours: 18; rightAscensionMinutes: 21; declination: -02.9; magnitude: 3.23 },
        Star { name: "Alphirk";           rightAscensionHours: 21; rightAscensionMinutes: 29; declination: +70.6; magnitude: 3.23 },
        Star { name: "";                  rightAscensionHours: 06; rightAscensionMinutes: 48; declination: -61.9; magnitude: 3.24 },
        Star { name: "";                  rightAscensionHours: 20; rightAscensionMinutes: 11; declination: -00.8; magnitude: 3.24 },
        Star { name: "";                  rightAscensionHours: 07; rightAscensionMinutes: 29; declination: -43.3; magnitude: 3.25 },
        Star { name: "";                  rightAscensionHours: 14; rightAscensionMinutes: 06; declination: -26.7; magnitude: 3.25 },
        Star { name: "Brachium";          rightAscensionHours: 15; rightAscensionMinutes: 04; declination: -25.3; magnitude: 3.25 },
        Star { name: "Sulaphat";          rightAscensionHours: 18; rightAscensionMinutes: 59; declination: +32.7; magnitude: 3.25 },
        Star { name: "";                  rightAscensionHours: 03; rightAscensionMinutes: 47; declination: -74.2; magnitude: 3.26 },
        Star { name: "";                  rightAscensionHours: 00; rightAscensionMinutes: 39; declination: +30.9; magnitude: 3.27 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 22; declination: -25.0; magnitude: 3.27 },
        Star { name: "Skat";              rightAscensionHours: 22; rightAscensionMinutes: 55; declination: -15.8; magnitude: 3.27 },
        Star { name: "";                  rightAscensionHours: 05; rightAscensionMinutes: 13; declination: -16.2; magnitude: 3.29 },
        Star { name: "";                  rightAscensionHours: 10; rightAscensionMinutes: 14; declination: -70.0; magnitude: 3.29 },
        Star { name: "Edasich";           rightAscensionHours: 15; rightAscensionMinutes: 25; declination: +59.0; magnitude: 3.29 },
        Star { name: "";                  rightAscensionHours: 04; rightAscensionMinutes: 34; declination: -55.0; magnitude: 3.30 },
        Star { name: "";                  rightAscensionHours: 10; rightAscensionMinutes: 32; declination: -61.7; magnitude: 3.30 },
        Star { name: "";                  rightAscensionHours: 13; rightAscensionMinutes: 50; declination: -42.5; magnitude: 3.30 },
        Star { name: "Propus";            rightAscensionHours: 06; rightAscensionMinutes: 15; declination: +22.5; magnitude: 3.31 },
        Star { name: "Rasalgethi";        rightAscensionHours: 17; rightAscensionMinutes: 15; declination: +14.4; magnitude: 3.31 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 25; declination: -56.4; magnitude: 3.31 },
        Star { name: "";                  rightAscensionHours: 01; rightAscensionMinutes: 06; declination: -46.7; magnitude: 3.32 },
        Star { name: "Gorgonea Tertia";   rightAscensionHours: 03; rightAscensionMinutes: 05; declination: +38.8; magnitude: 3.32 },
        Star { name: "Megrez";            rightAscensionHours: 12; rightAscensionMinutes: 15; declination: +57.0; magnitude: 3.32 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 12; declination: -43.2; magnitude: 3.32 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 59; declination: -09.8; magnitude: 3.32 },
        Star { name: "";                  rightAscensionHours: 19; rightAscensionMinutes: 07; declination: -27.7; magnitude: 3.32 },
        Star { name: "";                  rightAscensionHours: 04; rightAscensionMinutes: 14; declination: -62.5; magnitude: 3.33 },
        Star { name: "Chort";             rightAscensionHours: 11; rightAscensionMinutes: 14; declination: +15.4; magnitude: 3.33 },
        Star { name: "Asmidiske";         rightAscensionHours: 07; rightAscensionMinutes: 49; declination: -24.9; magnitude: 3.34 },
        Star { name: "Segin";             rightAscensionHours: 01; rightAscensionMinutes: 54; declination: +63.7; magnitude: 3.35 },
        Star { name: "Algjebbah";         rightAscensionHours: 05; rightAscensionMinutes: 24; declination: -02.4; magnitude: 3.35 },
        Star { name: "Alzirr";            rightAscensionHours: 06; rightAscensionMinutes: 45; declination: +12.9; magnitude: 3.35 },
        Star { name: "Muscida";           rightAscensionHours: 08; rightAscensionMinutes: 30; declination: +60.7; magnitude: 3.35 },
        Star { name: "";                  rightAscensionHours: 19; rightAscensionMinutes: 25; declination: +03.1; magnitude: 3.36 },
        Star { name: "";                  rightAscensionHours: 15; rightAscensionMinutes: 23; declination: -44.7; magnitude: 3.37 },
        Star { name: "Heze";              rightAscensionHours: 13; rightAscensionMinutes: 35; declination: -00.6; magnitude: 3.38 },
        Star { name: "";                  rightAscensionHours: 08; rightAscensionMinutes: 47; declination: +06.4; magnitude: 3.38 },
        Star { name: "Meissa";            rightAscensionHours: 05; rightAscensionMinutes: 35; declination: +09.9; magnitude: 3.39 },
        Star { name: "";                  rightAscensionHours: 10; rightAscensionMinutes: 17; declination: -61.3; magnitude: 3.39 },
        Star { name: "Auva";              rightAscensionHours: 12; rightAscensionMinutes: 56; declination: +03.4; magnitude: 3.39 },
        Star { name: "";                  rightAscensionHours: 22; rightAscensionMinutes: 11; declination: +58.2; magnitude: 3.39 },
        Star { name: "";                  rightAscensionHours: 04; rightAscensionMinutes: 29; declination: +15.9; magnitude: 3.40 },
        Star { name: "";                  rightAscensionHours: 01; rightAscensionMinutes: 28; declination: -43.3; magnitude: 3.41 },
        Star { name: "";                  rightAscensionHours: 04; rightAscensionMinutes: 01; declination: +12.5; magnitude: 3.41 },
        Star { name: "";                  rightAscensionHours: 13; rightAscensionMinutes: 50; declination: -41.7; magnitude: 3.41 },
        Star { name: "";                  rightAscensionHours: 15; rightAscensionMinutes: 12; declination: -52.1; magnitude: 3.41 },
        Star { name: "";                  rightAscensionHours: 20; rightAscensionMinutes: 45; declination: +61.8; magnitude: 3.41 },
        Star { name: "Homam";             rightAscensionHours: 22; rightAscensionMinutes: 41; declination: +10.8; magnitude: 3.41 },
        Star { name: "Mothallah";         rightAscensionHours: 01; rightAscensionMinutes: 53; declination: +29.6; magnitude: 3.42 },
        Star { name: "";                  rightAscensionHours: 16; rightAscensionMinutes: 00; declination: -38.4; magnitude: 3.42 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 46; declination: +27.7; magnitude: 3.42 },
        Star { name: "";                  rightAscensionHours: 20; rightAscensionMinutes: 45; declination: -66.2; magnitude: 3.42 },
        Star { name: "";                  rightAscensionHours: 09; rightAscensionMinutes: 11; declination: -58.9; magnitude: 3.43 },
        Star { name: "Adhafera";          rightAscensionHours: 10; rightAscensionMinutes: 17; declination: +23.4; magnitude: 3.43 },
        Star { name: "Althalimain";       rightAscensionHours: 19; rightAscensionMinutes: 06; declination: -04.9; magnitude: 3.43 },
        Star { name: "Tania Borealis";    rightAscensionHours: 10; rightAscensionMinutes: 17; declination: +42.9; magnitude: 3.45 },
        Star { name: "Sheliak";           rightAscensionHours: 18; rightAscensionMinutes: 50; declination: +33.4; magnitude: 3.45 },
        Star { name: "Achird";            rightAscensionHours: 00; rightAscensionMinutes: 49; declination: +57.8; magnitude: 3.46 },
        Star { name: "Dheneb";            rightAscensionHours: 01; rightAscensionMinutes: 09; declination: -10.2; magnitude: 3.46 },
        Star { name: "";                  rightAscensionHours: 07; rightAscensionMinutes: 57; declination: -53.0; magnitude: 3.46 },
        Star { name: "";                  rightAscensionHours: 15; rightAscensionMinutes: 16; declination: +33.3; magnitude: 3.46 },
        Star { name: "Kaffaljidhma";      rightAscensionHours: 02; rightAscensionMinutes: 43; declination: +03.2; magnitude: 3.47 },
        Star { name: "";                  rightAscensionHours: 10; rightAscensionMinutes: 07; declination: +16.8; magnitude: 3.48 },
        Star { name: "";                  rightAscensionHours: 16; rightAscensionMinutes: 43; declination: +38.9; magnitude: 3.48 },
        Star { name: "";                  rightAscensionHours: 01; rightAscensionMinutes: 44; declination: -15.9; magnitude: 3.49 },
        Star { name: "";                  rightAscensionHours: 07; rightAscensionMinutes: 02; declination: -27.9; magnitude: 3.49 },
        Star { name: "Alula Borealis";    rightAscensionHours: 11; rightAscensionMinutes: 18; declination: +33.1; magnitude: 3.49 },
        Star { name: "Nekkar";            rightAscensionHours: 15; rightAscensionMinutes: 02; declination: +40.4; magnitude: 3.49 },
        Star { name: "";                  rightAscensionHours: 18; rightAscensionMinutes: 27; declination: -46.0; magnitude: 3.49 },
        Star { name: "";                  rightAscensionHours: 22; rightAscensionMinutes: 49; declination: -51.3; magnitude: 3.49 },
        Star { name: "";                  rightAscensionHours: 06; rightAscensionMinutes: 50; declination: -32.5; magnitude: 3.50 },
        Star { name: "Wasat";             rightAscensionHours: 07; rightAscensionMinutes: 20; declination: +22.0; magnitude: 3.50 },
        Star { name: "";                  rightAscensionHours: 22; rightAscensionMinutes: 50; declination: +66.2; magnitude: 3.50 },
        Star { name: "";                  rightAscensionHours: 19; rightAscensionMinutes: 59; declination: +19.5; magnitude: 3.51 },
        Star { name: "Sadalbari";         rightAscensionHours: 22; rightAscensionMinutes: 50; declination: +24.6; magnitude: 3.51 },
        Star { name: "Rana";              rightAscensionHours: 03; rightAscensionMinutes: 43; declination: -09.8; magnitude: 3.52 },
        Star { name: "Subra";             rightAscensionHours: 09; rightAscensionMinutes: 41; declination: +09.9; magnitude: 3.52 },
        Star { name: "Tseen Ke";          rightAscensionHours: 09; rightAscensionMinutes: 57; declination: -54.6; magnitude: 3.52 },
        Star { name: "";                  rightAscensionHours: 18; rightAscensionMinutes: 58; declination: -21.1; magnitude: 3.52 },
        Star { name: "Baham";             rightAscensionHours: 22; rightAscensionMinutes: 10; declination: +06.2; magnitude: 3.52 },
        Star { name: "Ain";               rightAscensionHours: 04; rightAscensionMinutes: 29; declination: +19.2; magnitude: 3.53 },
        Star { name: "Tarf";              rightAscensionHours: 08; rightAscensionMinutes: 17; declination: +09.2; magnitude: 3.53 },
        Star { name: "";                  rightAscensionHours: 11; rightAscensionMinutes: 33; declination: -31.9; magnitude: 3.54 },
        Star { name: "";                  rightAscensionHours: 15; rightAscensionMinutes: 50; declination: -03.4; magnitude: 3.54 },
        Star { name: "";                  rightAscensionHours: 17; rightAscensionMinutes: 38; declination: -15.4; magnitude: 3.54 }*/
    ]

    // -----------------------------------------------------------------------

    Component.onCompleted:
    {
        var minMagnitude = stars[stars.length - 1].magnitude;
        var maxMagnitude = stars[0].magnitude;
        var range = minMagnitude - maxMagnitude;

        for (var starIdx = 0; starIdx < stars.length; ++starIdx)
        {
            var star = stars[starIdx];
            star.displayedSize = 4 * (1.0 - 0.75 * (star.magnitude - maxMagnitude) / range);
        }
    }
}

